name: E2E Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Run e2e tests with Docker Compose
      env:
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ACCESS_TTL: ${{ secrets.ACCESS_TTL }}
        JWT_TTL: ${{ secrets.JWT_TTL }}
        PORT: ${{ secrets.PORT }}
        HOST: ${{ secrets.HOST }}
        CLI_USER_NAME: ${{ secrets.CLI_USER_NAME }}
        CLI_USER_FIRST_NAME: ${{ secrets.CLI_USER_FIRST_NAME }}
        CLI_USER_LAST_NAME: ${{ secrets.CLI_USER_LAST_NAME }}
        CLI_USER_EMAIL: ${{ secrets.CLI_USER_EMAIL }}
        CLI_USER_PASSWORD: ${{ secrets.CLI_USER_PASSWORD }}
      run: pnpm dockerize:e2e
